import sys, os, datetime
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)
import db

# pip install google_auth_oauthlib google-api-python-client
import google_auth_oauthlib.flow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
import googleapiclient.discovery
import googleapiclient.errors
import googleapiclient.http

scopes = ['https://www.googleapis.com/auth/youtube']

api_service_name = "youtube"
api_version = "v3"

def get_mac():
    return db.get_setting('mac')[-6:]
    # mac_num = uuid.getnode()
    # mac_str = f"{mac_num:012X}"
    # last_6 = mac_str[-6:]
    # return last_6

def auth():
    credentials = db.get_credentials()

    # 기존 인증 정보 사용
    if credentials is not None:
        credentials = Credentials.from_authorized_user_info(credentials)
        if not credentials.valid: #만약 만료된 경우
            request = Request()
            credentials.refresh(request)
            db.update_credentials(credentials.to_json())

    # 새로 인증은 안 함
    youtube = googleapiclient.discovery.build(
        api_service_name, api_version, credentials=credentials)
    return youtube

def re_auth():
    secret = db.get_secret()
    if secret is not None:
        flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_config(secret,scopes)
        credentials = flow.run_local_server(port=0)
        db.update_credentials(credentials.to_json())
        youtube = googleapiclient.discovery.build(
            api_service_name, api_version, credentials=credentials)
        return youtube
    else:
        return None

def create_broadcast(title,desc,youtube):
    # Disable OAuthlib's HTTPS verification when running locally.
    # *DO NOT* leave this option enabled in production.
    # os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

    now = datetime.datetime.now(tz=datetime.timezone.utc)
    start_time = now.isoformat(timespec='milliseconds')

    request = youtube.liveBroadcasts().insert(
        part="snippet,contentDetails,status",
        body={
            "contentDetails": {
                "closedCaptionsType": "closedCaptionsDisabled",
                "enableDvr": True,
                "enableEmbed": True,
                "recordFromStart": True,
                "enableAutoStart": True,
                "enableAutoStop": True,
                "latencyPreference" : 'ultraLow'
            },
            "snippet": {
                "title": title,
                "description" : desc,
                "scheduledStartTime": start_time,
            },
            "status": {
                "privacyStatus": "public",
                "selfDeclaredMadeForKids" : False
            }
        }
    )
    response = request.execute()
    broadcast_id = response['id']

    youtube.liveBroadcasts().bind(
        part="id,contentDetails",
        id=broadcast_id,  
        streamId=db.get_setting('channel_stream_id')
    ).execute()

    db.update_temp('broadcast_id',broadcast_id)

def broadcast_live(youtube):
    broadcast_id = db.get_temp('broadcast_id')
    youtube.liveBroadcasts().transition(
        broadcastStatus="live",
        id=broadcast_id,
        part="status"
    ).execute()

def broadcast_comp(youtube):
    broadcast_id = db.get_temp('broadcast_id')
    youtube.liveBroadcasts().transition(
        broadcastStatus="complete",
        id=broadcast_id,
        part="status"
    ).execute()

## TOOD : 계정 스트림 키 가져오는 함수 추가
def get_stream_key(youtube):
    request = youtube.liveStreams().list(
        part="snippet,cdn,status",
        mine=True,
        maxResults=50
    )
    response = request.execute()

    for stream in response.get('items', []):
        if stream['snippet']['title'] == f'LiveKiosk Stream Key {get_mac()}':
            return stream['cdn']['ingestionInfo']['streamName'], stream['id']
    return create_stream_key(youtube)

def get_channel_name(youtube):
    request = youtube.channels().list(
        part="snippet",
        mine=True
    )
    response = request.execute()

    if response['items']:
        channel = response['items'][0]
        title = channel['snippet']['title']
        channel_id = channel['id']
        return f'{title} (ID : {channel_id})'
    else:
        return "채널 정보를 찾을 수 없습니다."

def create_stream_key(youtube):
    stream_title = f'LiveKiosk Stream Key {get_mac()}'
    stream_desc = 'LiveKiosk (OBS Studio 기반 무인 자동화 스트리밍 키오스크 프로그램)에서 자동으로 생성한 스트림 키입니다. Auto generated by LiveKiosk, a non-human automatic straming kiosk program based on OBS Studio.'
    
    request : googleapiclient.http.HttpRequest = youtube.liveStreams().insert(
        part="snippet,cdn,contentDetails",
        body={
            "snippet": {
                "title": stream_title,
                "description": stream_desc
            },
            "cdn": {
                "frameRate": "variable",
                "ingestionType": "rtmp",
                "resolution": "variable"
            },
            "contentDetails": {
                "isReusable": True
            }
        }
    )

    response = request.execute()
    # result = f'스트림 키 : {response['cdn']['ingestionInfo']['streamName']}\nRTMP 서버 주소 : {response['cdn']['ingestionInfo']['ingestionAddress']}'
    return response['cdn']['ingestionInfo']['streamName'], response['id']
